### PR TITLE
Fulma minimal template - URL Change

### PR DESCRIPTION
**Pull request by getkks**
Updated the url from https://mangelmaxime.github.io/Fulma/#template to https://fulma.github.io/Fulma/

### CODE REVIEW

**Comment by MangelMaxime** [comment]
You can keep `#template` at the end of the URL so the right page is loaded by default. :)

**Comment by kunjee17** [comment]
@MangelMaxime should we take this PR ?

**Comment by MangelMaxime** [comment]
Yes, with `#template` added to the end of the URL otherwise the page loaded is not the one about the template.

So correct URL: https://fulma.github.io/Fulma/#template

**Comment by kunjee17** [comment]
@getkks can you please make necessary changes (don't remove `template` but do update the url part. ). I ll merge it then.

**Comment by kunjee17** [comment]
I guess things are already in.

**Pull request closed without merging**
